### ISSUE TITLE
Management-ul melodiilor/albumelor/playlists

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/MusicalBash#10]
De implementat clasele Song, Album, Playlist, Index

- [ ] Song
- [ ] Album
- [ ] Playlist
- [ ] Index

Song, Album, Playlist, sunt self-explanatory
Index o sa fie capabil sa incare din hdd/ssd indexul melodiilor, datele aferente, si sa raspunda la GetAlbums(), GetAllSongs(),  ......

**Comment by theodormoroianu** [comment]
Clasa player poate sa faca toate acestea.
