### ISSUE TITLE
FileSystemHandler

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/MusicalBash#11]
Avem nevoie de un namespace care sa ne faciliteze crearea, verificarea existentelor fisierelor de configurare, si salvarea periodica a stats-urilor

**Comment by theodormoroianu** [comment]
From c++17 there is in the c++ standard the filesistem class that basically does anything we could wish for.
Check [here](https://en.cppreference.com/w/cpp/filesystem/directory_entry)

**Comment by theodormoroianu** [comment]
Trebuie facuta o comanda care primeste un path si returneaza un vector cu toata muzica din folder si subfoldere, impartite dupa folderul din care vin.

**Comment by Rpd-Strike** [comment]
Implemented as of Release [v0.1](https://github.com/TeamUnibuc/MusicalBash/releases/tag/v0.1)
