### ISSUE TITLE
No way to add song to playlist

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/MusicalBash#38]
Currently there is no way to add a song to some specific playlist.

**Comment by theodormoroianu** [comment]
I think the playlist menu (when the music inside a playlist is displayed) there should be a (+) button what calls the `AddSongToPlaylist` command.
Another uglier alternative is to use (again) zenity list, to let the user select the playlist he wants to add a song into and then call the `AddSongToPlaylist` command.

**Comment by Rpd-Strike** [comment]
Solved by #54
