### ISSUE TITLE
Make install

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/MusicalBash#43]
We should implement a command in the makefile that installs the prerequisite packages for debian/ubuntu.

Installing packages for other distros is left as an exercise to the user of the program :)))))

**Comment by theodormoroianu** [comment]
I just added a `install.sh` script in the root folder of the project.
The script should be run as root, and installs the depedencies from the `README.md` file.

If you aren't able to run the script make sure it is executable by using
`chmod +x install.sh`

**Comment by Rpd-Strike** [comment]
Can we make it so that it works from the makefile? A command like make install, or sudo make install?
