### ISSUE TITLE
Music erased from disc

### ISSUE THREAD

**Issue by theodormoroianu** [TeamUnibuc/MusicalBash#47]
What happends when a music (from a playlist) is removed from the disk?
If it is done while the app is closed it sould be ok after adding a few try / catches (if we can't load a music then skip it).
But what happends if a music is removed while the app is running and the `PMusic` pointer exists but is referring to a deleted music?
In it's actual form the app will simply crash when the player tries to add an invalid `PMusic` pointer to the `PMusicPlayer` class.

**Comment by Rpd-Strike** [comment]
Solved by PR #51
