### ISSUE TITLE
Clasificari melodii

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/MusicalBash#8]
Cum procedam in privinta metadata-urilor pentru melodii.
Stocam pentru fiecare melodie un  autor/album/an?

Daca da, cum facem asta. Putem folosi Mp3 metadata pentru asta (sunt tinute in fisier .mp3 efectiv), sau facem noi local un fisier ascuns in care tinem metadata pentru fiecare fisier
Dar daca folosim mp3 builtin metadata, cum facem cu alte extensii?

**Comment by theodormoroianu** [comment]
Cel mai ok e sa facem direct pe foldere.
Daca userul a adaugat folderul `foo\` si in el se gaseste subfolderul `bar\` atunci automat tot ce se gaseste imediat in `foo` este in albumul `foo` si tot ce este in `bar` este in albumul `bar`.

Practic am vrea cv de genu:
```c++
void Explore(Path) {
    for (fisier in Path)
        AddToAlbum(Path, fisier);
    for (folder in Path)
        Explore(Path + folder); 
}
````

**Comment by Rpd-Strike** [comment]
Si daca cineva vrea sa stearga o melodie specific? Sau sa adauge una, specific?
Folosim doar AddToAlbum, si eventual un RemoveSong?

**Comment by Rpd-Strike** [comment]
Folosim Sqlite pentru stocarea melodiilor, daca stocam informatii aditionale o sa cream alte Pull Requests.
