### ISSUE TITLE
Cum tratam cazurile cand fisierele apar/dispar, sau intregi foldere

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/MusicalBash#9]
Sa zicem ca noi "urmarim" o melodie la o locatie $path. Daca din senin, fisierul este sters de pe sistem, ce facem, pur si simplu la rulari succesive ignoram ca a disparut o melodie si "updatam" "indexul" de melodii. Putem sa mai dam un warning cand ne dam seama (catre utilizator).

Si in general, cum facem sistemul de a urmarii fisiere, pentru ca ar trebui sa mentinem un index cu ce fisiere playable mentinem

**Comment by Rpd-Strike** [comment]
O melodie consta in  

> absolute-path **\/** nume-melodie **.** extensie
Si asta este ceea ce consideram o melodie distincta in toata colectia.
In care asupra unei melodii mai mentinem si nistea stats

**Comment by theodormoroianu** [comment]
Putem efectiv inainte sa facem cv cu o melodie (sa ii dam play / sa o afisam pe ecran / sa o includem intr-o numaratoare) sa verificam daca exista. 
Daca este stearsa in timp ce se da play atunci aruncam o exceptie care este prinsa de player (trece la melodia urmatoare), si da un warning.

**Comment by Rpd-Strike** [comment]
Deocamndata nu tratam 

> Putem efectiv inainte sa facem cv cu o melodie (sa ii dam play / sa o afisam pe ecran / sa o includem intr-o numaratoare) sa verificam daca exista.
> Daca este stearsa in timp ce se da play atunci aruncam o exceptie care este prinsa de player (trece la melodia urmatoare), si da un warning.

Buna idee, asa facem

**Comment by Rpd-Strike** [comment]
New problem occurs occasionally, although is very very obscure.

For rechecking the downloads directory, we check if an object of type PMusic is created with no errors. However in some cases the PMusic object can be created even if it's a partially downloaded mp3 file. This leads to the song being added in the Downloads album and having a song duration shorter than the actual song, and if we try to play this song, there is a progress bar bug.

**Comment by Rpd-Strike** [comment]
duplicate of #47
